import { IComponent } from "./IComponent";
declare const dashboard = "dashboard";
declare const dashboardList = "dashboardList";
declare const stack = "stack";
declare const list = "list";
declare const hsplit = "hsplit";
declare const vsplit = "vsplit";
declare const win = "window";
declare const isSplit: (comp: IComponent) => boolean;
export { dashboard, dashboardList, stack, list, hsplit, vsplit, win as window, isSplit };
