import IMasterEntitySourceKey from "./IMasterEntitySourceKey";

interface IMasterEntitySourceEntityAddress extends IMasterEntitySourceKey {
    sourceEntityAddressId?: string;
    addressMatchKeyCd?: string;
    addressSiteLatitude?: string;
    addressSiteLongitude?: string;
    streetLocalityPointLatitude?: string;
    streetLocalityPointLongitude?: string;
    localityPointLatitude?: string;
    localityPointLongitude?: string;
    usageTypeCd?: string;
    standardAddressValue?: string;
    lotId?: string;
    unitTypeAbbreviation?: string;
    unitId?: string;
    levelTypeAbbreviation?: string;
    levelId?: string;
    roadFirstPartId?: string;
    roadSecondPartId?: string;
    roadName?: string;
    roadTypeAbbreviation?: string;
    roadSuffixAbbreviation?: string;
    addressSiteName?: string;
    localityName?: string;
    stateCd?: string;
    postalCd?: string;
    countryCd?: string;
    administrationArea?: string;
    supraAdministrationArea?: string;
    subAdministrationArea?: string;
    postalDeliveryTypeAbbreviation?: string;
    postalDeliveryId?: string;
    deliveryPointId?: string;
    unparsedAddress?: string;
    identifiedContactValue?: string;
    usageTypeCdGeo?: string;
    standardAddressValueGeo?: string;
    lotIdGeo?: string;
    unitTypeAbbreviationGeo?: string;
    unitIdGeo?: string;
    levelTypeAbbreviationGeo?: string;
    levelIdGeo?: string;
    roadFirstPartIdGeo?: string;
    roadSecondPartIdGeo?: string;
    roadNameGeo?: string;
    roadTypeAbbreviationGeo?: string;
    roadSuffixAbbreviationGeo?: string;
    addressSiteNameGeo?: string;
    localityNameGeo?: string;
    stateCdGeo?: string;
    postalCdGeo?: string;
    countryCdGeo?: string;
    postalDeliveryTypeAbbreviationGeo?: string;
    postalDeliveryIdGeo?: string;
    deliveryPointIdGeo?: string;
    addressSitePID?: string;
    addressDetailPID?: string;
    streetLocalityPID?: string;
    localityPID?: string;
    statePID?: string;
    effectiveStartDt?: string;
    [key : string] : any;
}

export { IMasterEntitySourceEntityAddress as default, IMasterEntitySourceEntityAddress };