import {
    IMasterEntityDataService,
    IMasterEntityServiceRequestOptions,
    IMasterEntitySourceRefResponse,
    IMasterEntitySourceEntityMetaResponse,
    IMasterEntitySourceEntityNameResponse,
    IMasterEntitySourceEntityAddressResponse,
    IMasterEntitySourceEntityPhoneResponse,
    IMasterEntitySourceEntityCredentialResponse
} from "./IMasterEntityDataService";
import IMasterEntitySourceRef from "./IMasterEntitySourceRef";
import IMasterEntitySourceEntityMeta from "./IMasterEntitySourceEntityMeta";
import IMasterEntitySourceEntityName from "./IMasterEntitySourceEntityName";
import IMasterEntitySourceEntityAddress from "./IMasterEntitySourceEntityAddress";
import IMasterEntitySourceEntityPhone from "./IMasterEntitySourceEntityPhone";
import IMasterEntitySourceEntityCredential from "./IMasterEntitySourceEntityCredential";

const sourceSystemCodes = ["ABR","ASIC","BAGS","ICS","DGMS","EROLL","EXAM","IATA","INTCP","IAT"];

const createRefResponse = (masterEntityId : string) : IMasterEntitySourceRefResponse => {
    const r = {
        getMasterEntitySourceResponse: [
            {
                "masterEntityId": masterEntityId,
                "sourceEntityId": "604455673",
                "masterSourceSystemCd": "EROLL",
                "masterSourceObjectTypeCd": "EROLL_IND",
                "masterSourceKeyValue": "24470460",
                "MDMProfileName": "IND_NM_ADRS",
                "masteredIndicator": "Y",
                "MDMMatchScorePercent": "96",
                "sourceSystemCd": "ABR",
                "sourceObjectTypeCd": "ABR_AGENCY_IND",
                "sourceKeyValue": "8404",
                "sourceRelatedKeyValue": "8404",
                "masterEntityNameID": "34367802",
                "masterEntityAddressID": "34367803",
                "masterEntityCredentialID": "",
                "masterEntityEmailID": "",
                "masterEntityPhoneID": "",
                "sourceEntityNameId": "713541715",
                "sourceEntityAddressId": "669245190",
                "sourceEntityCredentialId": "",
                "sourceEntityEmailId": "",
                "sourceEntityPhoneId": "",
                "masterValidStartTmstmp": "2015-04-01 15:51:25.780000",
                "sourceValidStartTmstmp": "2006-01-01 00:00:00.000000",
                "CDLStartTmstmp": "2016-09-16 15:07:25.900000"
            }, {
                "masterEntityId": masterEntityId,
                "sourceEntityId": "732560948",
                "masterSourceSystemCd": "EROLL",
                "masterSourceObjectTypeCd": "EROLL_IND",
                "masterSourceKeyValue": "24470460",
                "MDMProfileName": "IND_BIO_NM_ADRS",
                "masteredIndicator": "Y",
                "MDMMatchScorePercent": "100",
                "sourceSystemCd": "ASIC",
                "sourceObjectTypeCd": "ASIC_IND",
                "sourceKeyValue": "16794911",
                "sourceRelatedKeyValue": "16794911",
                "masterEntityNameID": "34367802",
                "masterEntityAddressID": "34367803",
                "masterEntityCredentialID": "",
                "masterEntityEmailID": "",
                "masterEntityPhoneID": "",
                "sourceEntityNameId": "1006361313",
                "sourceEntityAddressId": "895055752",
                "sourceEntityCredentialId": "",
                "sourceEntityEmailId": "",
                "sourceEntityPhoneId": "",
                "masterValidStartTmstmp": "2015-04-01 15:51:25.780000",
                "sourceValidStartTmstmp": "2007-07-27 00:00:00.000000",
                "CDLStartTmstmp": "2016-09-16 18:01:33.310000"
            }, {
                "masterEntityId": masterEntityId,
                "sourceEntityId": masterEntityId,
                "masterSourceSystemCd": "EROLL",
                "masterSourceObjectTypeCd": "EROLL_IND",
                "masterSourceKeyValue": "24470460",
                "MDMProfileName": "InitLd_RefData_DIRECT_MST",
                "masteredIndicator": "Y",
                "MDMMatchScorePercent": "",
                "sourceSystemCd": "EROLL",
                "sourceObjectTypeCd": "EROLL_IND",
                "sourceKeyValue": "24470460",
                "sourceRelatedKeyValue": "24470460",
                "masterEntityNameID": "",
                "masterEntityAddressID": "",
                "masterEntityCredentialID": "",
                "masterEntityEmailID": "",
                "masterEntityPhoneID": "",
                "sourceEntityNameId": "",
                "sourceEntityAddressId": "",
                "sourceEntityCredentialId": "",
                "sourceEntityEmailId": "",
                "sourceEntityPhoneId": "",
                "masterValidStartTmstmp": "2015-04-01 15:51:25.780000",
                "sourceValidStartTmstmp": "2015-04-01 15:51:25.780000",
                "CDLStartTmstmp": "2016-09-16 08:55:54.000000"
            }, {
                "masterEntityId": masterEntityId,
                "sourceEntityId": "746788568",
                "masterSourceSystemCd": "EROLL",
                "masterSourceObjectTypeCd": "EROLL_IND",
                "masterSourceKeyValue": "24470460",
                "MDMProfileName": "IND_BIO_NM_CRED",
                "masteredIndicator": "Y",
                "MDMMatchScorePercent": "91",
                "sourceSystemCd": "IAT",
                "sourceObjectTypeCd": "IAT_PAX",
                "sourceKeyValue": "0003500491",
                "sourceRelatedKeyValue": "0003500491",
                "masterEntityNameID": "34367802",
                "masterEntityAddressID": "",
                "masterEntityCredentialID": "1079844132",
                "masterEntityEmailID": "",
                "masterEntityPhoneID": "",
                "sourceEntityNameId": "896845850",
                "sourceEntityAddressId": "",
                "sourceEntityCredentialId": "1022194506",
                "sourceEntityEmailId": "",
                "sourceEntityPhoneId": "",
                "masterValidStartTmstmp": "2015-04-01 15:51:25.780000",
                "sourceValidStartTmstmp": "2005-11-22 11:45:24.000000",
                "CDLStartTmstmp": "2016-09-20 05:38:40.720000"
            }, {
                "masterEntityId": masterEntityId,
                "sourceEntityId": "1493584953",
                "masterSourceSystemCd": "ICS",
                "masterSourceObjectTypeCd": "ICS_CLNT",
                "masterSourceKeyValue": "642531359192207",
                "MDMProfileName": "LEFTOVER - NEW ROW",
                "masteredIndicator": "N",
                "MDMMatchScorePercent": "",
                "sourceSystemCd": "ICS",
                "sourceObjectTypeCd": "ICS_CLNT",
                "sourceKeyValue": "642531359192207",
                "sourceRelatedKeyValue": "642531359192207",
                "masterEntityNameID": "34367802",
                "masterEntityAddressID": "",
                "masterEntityCredentialID": "",
                "masterEntityEmailID": "",
                "masterEntityPhoneID": "",
                "sourceEntityNameId": "149358495312",
                "sourceEntityAddressId": "",
                "sourceEntityCredentialId": "",
                "sourceEntityEmailId": "",
                "sourceEntityPhoneId": "",
                "masterValidStartTmstmp": "2017-01-22 19:19:53.135073",
                "sourceValidStartTmstmp": "2017-01-22 19:19:53.135073",
                "CDLStartTmstmp": "2017-04-11 17:25:40.340000"
            }, {
                "masterEntityId": masterEntityId,
                "sourceEntityId": "280514359",
                "masterSourceSystemCd": "BAGS",
                "masterSourceObjectTypeCd": "BAGS_CLNT",
                "masterSourceKeyValue": "N7107645|AUS|19880121|M",
                "MDMProfileName": "LEFTOVER - NEW ROW",
                "masteredIndicator": "N",
                "MDMMatchScorePercent": "",
                "sourceSystemCd": "BAGS",
                "sourceObjectTypeCd": "BAGS_CLNT",
                "sourceKeyValue": "N7107645|AUS|19880121|M",
                "sourceRelatedKeyValue": "N7107645|AUS|19880121|M",
                "masterEntityNameID": "34367802",
                "masterEntityAddressID": "",
                "masterEntityCredentialID": "",
                "masterEntityEmailID": "",
                "masterEntityPhoneID": "",
                "sourceEntityNameId": "28051435912",
                "sourceEntityAddressId": "",
                "sourceEntityCredentialId": "",
                "sourceEntityEmailId": "",
                "sourceEntityPhoneId": "",
                "masterValidStartTmstmp": "2017-01-22 19:19:53.135073",
                "sourceValidStartTmstmp": "2017-01-22 19:19:53.135073",
                "CDLStartTmstmp": "2017-04-11 17:25:40.340000"
            }, {
                "masterEntityId": masterEntityId,
                "sourceEntityId": "1362633444",
                "masterSourceSystemCd": "DGMS",
                "masterSourceObjectTypeCd": "DGMS_CLNT",
                "masterSourceKeyValue": "677034",
                "MDMProfileName": "LEFTOVER - NEW ROW",
                "masteredIndicator": "N",
                "MDMMatchScorePercent": "",
                "sourceSystemCd": "DGMS",
                "sourceObjectTypeCd": "DGMS_CLNT",
                "sourceKeyValue": "677034",
                "sourceRelatedKeyValue": "677034",
                "masterEntityNameID": "34367802",
                "masterEntityAddressID": "",
                "masterEntityCredentialID": "",
                "masterEntityEmailID": "",
                "masterEntityPhoneID": "",
                "sourceEntityNameId": "136263344412",
                "sourceEntityAddressId": "",
                "sourceEntityCredentialId": "",
                "sourceEntityEmailId": "",
                "sourceEntityPhoneId": "",
                "masterValidStartTmstmp": "2017-01-22 19:19:53.135073",
                "sourceValidStartTmstmp": "2017-01-22 19:19:53.135073",
                "CDLStartTmstmp": "2017-04-11 17:25:40.340000"
            },
            {
                "masterEntityId": masterEntityId,
                "sourceEntityId": "1362633445",
                "masterSourceSystemCd": "EXAMS",
                "masterSourceObjectTypeCd": "EXAMS",
                "masterSourceKeyValue": "677034",
                "MDMProfileName": "LEFTOVER - NEW ROW",
                "masteredIndicator": "N",
                "MDMMatchScorePercent": "",
                "sourceSystemCd": "EXAM",
                "sourceObjectTypeCd": "EXAMS",
                "sourceKeyValue": "677034",
                "sourceRelatedKeyValue": "677034",
                "masterEntityNameID": "34367802",
                "masterEntityAddressID": "",
                "masterEntityCredentialID": "",
                "masterEntityEmailID": "",
                "masterEntityPhoneID": "",
                "sourceEntityNameId": "136263344412",
                "sourceEntityAddressId": "",
                "sourceEntityCredentialId": "",
                "sourceEntityEmailId": "",
                "sourceEntityPhoneId": "",
                "masterValidStartTmstmp": "2017-01-22 19:19:53.135073",
                "sourceValidStartTmstmp": "2017-01-22 19:19:53.135073",
                "CDLStartTmstmp": "2017-04-11 17:25:40.340000"
            }, {
                "masterEntityId": masterEntityId,
                "sourceEntityId": "1362633446",
                "masterSourceSystemCd": "EROLL",
                "masterSourceObjectTypeCd": "EROLL_IND",
                "masterSourceKeyValue": "24470460",
                "MDMProfileName": "IND_BIO_NM_CRED",
                "masteredIndicator": "Y",
                "MDMMatchScorePercent": "91",
                "sourceSystemCd": "IATA",
                "sourceObjectTypeCd": "IATA_PAX",
                "sourceKeyValue": "000435455500491",
                "sourceRelatedKeyValue": "000435455500491",
                "masterEntityNameID": "34367802",
                "masterEntityAddressID": "",
                "masterEntityCredentialID": "1079844132",
                "masterEntityEmailID": "",
                "masterEntityPhoneID": "",
                "sourceEntityNameId": "12896845850",
                "sourceEntityAddressId": "",
                "sourceEntityCredentialId": "1022194506",
                "sourceEntityEmailId": "",
                "sourceEntityPhoneId": "",
                "masterValidStartTmstmp": "2015-04-01 15:51:25.780000",
                "sourceValidStartTmstmp": "2005-11-22 11:45:24.000000",
                "CDLStartTmstmp": "2016-09-20 05:38:40.720000"
            }, {
                "masterEntityId": masterEntityId,
                "sourceEntityId": "1362633447",
                "masterSourceSystemCd": "EROLL",
                "masterSourceObjectTypeCd": "EROLL_IND",
                "masterSourceKeyValue": "24470460",
                "MDMProfileName": "IND_BIO_NM_CRED",
                "masteredIndicator": "Y",
                "MDMMatchScorePercent": "91",
                "sourceSystemCd": "INTCP",
                "sourceObjectTypeCd": "INTCP_PAX",
                "sourceKeyValue": "000435455500491",
                "sourceRelatedKeyValue": "000435455500491",
                "masterEntityNameID": "34367802",
                "masterEntityAddressID": "",
                "masterEntityCredentialID": "1079844132",
                "masterEntityEmailID": "",
                "masterEntityPhoneID": "",
                "sourceEntityNameId": "12896845850",
                "sourceEntityAddressId": "",
                "sourceEntityCredentialId": "1022194506",
                "sourceEntityEmailId": "",
                "sourceEntityPhoneId": "",
                "masterValidStartTmstmp": "2015-04-01 15:51:25.780000",
                "sourceValidStartTmstmp": "2005-11-22 11:45:24.000000",
                "CDLStartTmstmp": "2016-09-20 05:38:40.720000"
            }
        ]
    };
    r.getMasterEntitySourceResponse = r.getMasterEntitySourceResponse.filter(r => sourceSystemCodes.indexOf(r.sourceSystemCd) >= 0);
    return r;
};

const createMetaResponse = (masterEntityId : string) : IMasterEntitySourceEntityMetaResponse => {
    const r = {
        getMasterEntitySourceEntityResponse: [
            {
                "masterEntityId": masterEntityId,
                "sourceEntityId": "1",
                "sourceSystemCd": "EROLL",
                "entityTypeCd": "IND",
                "sex": "MALE",
                "birthDt": "1973-02-17",
                "birthCountryCd": "",
                "effectiveStartDt": "2015-04-01"
            },
            {
                "masterEntityId": masterEntityId,
                "sourceEntityId": "604455673",
                "sourceSystemCd": "ABR",
                "entityTypeCd": "IND",
                "sex": "NA",
                "birthDt": "",
                "birthCountryCd": "",
                "effectiveStartDt": "2006-01-01"
            },
            {
                "masterEntityId": masterEntityId,
                "sourceEntityId": "732560948",
                "sourceSystemCd": "ASIC",
                "entityTypeCd": "IND",
                "sex": "NA",
                "birthDt": "1973-02-17",
                "birthCountryCd": "",
                "effectiveStartDt": "2007-07-27"
            },
            {
                "masterEntityId": masterEntityId,
                "sourceEntityId": "746788568",
                "sourceSystemCd": "IAT",
                "entityTypeCd": "IND",
                "sex": "MALE",
                "birthDt": "1973-02-17",
                "birthCountryCd": "AUS",
                "effectiveStartDt": "2005-11-22"
            },
            {
                "masterEntityId": masterEntityId,
                "sourceEntityId": "1493584953",
                "sourceSystemCd": "ICS",
                "entityTypeCd": "IND",
                "sex": "MALE",
                "birthDt": "1973-02-17",
                "birthCountryCd": "AUS",
                "effectiveStartDt": "2005-11-22"
            },
            {
                "masterEntityId": masterEntityId,
                "sourceEntityId": "280514359",
                "sourceSystemCd": "BAGS",
                "entityTypeCd": "IND",
                "sex": "MALE",
                "birthDt": "1973-02-17",
                "birthCountryCd": "AUS",
                "effectiveStartDt": "2005-11-22"
            },
            {
                "masterEntityId": masterEntityId,
                "sourceEntityId": "1362633444",
                "sourceSystemCd": "DGMS",
                "entityTypeCd": "IND",
                "sex": "MALE",
                "birthDt": "1973-02-17",
                "birthCountryCd": "AUS",
                "effectiveStartDt": "2005-11-22"
            },
            {
                "masterEntityId": masterEntityId,
                "sourceEntityId": "1362633445",
                "sourceSystemCd": "EXAM",
                "entityTypeCd": "IND",
                "sex": "MALE",
                "birthDt": "1973-02-17",
                "birthCountryCd": "AUS",
                "effectiveStartDt": "2005-11-22"
            },
            {
                "masterEntityId": masterEntityId,
                "sourceEntityId": "1362633446",
                "sourceSystemCd": "IATA",
                "entityTypeCd": "IND",
                "sex": "MALE",
                "birthDt": "1973-02-17",
                "birthCountryCd": "AUS",
                "effectiveStartDt": "2005-11-22"
            },
            {
                "masterEntityId": masterEntityId,
                "sourceEntityId": "1362633447",
                "sourceSystemCd": "INTCP",
                "entityTypeCd": "IND",
                "sex": "MALE",
                "birthDt": "1973-02-17",
                "birthCountryCd": "AUS",
                "effectiveStartDt": "2005-11-22"
            }
        ]
    };
    r.getMasterEntitySourceEntityResponse = r.getMasterEntitySourceEntityResponse.filter(r => sourceSystemCodes.indexOf(r.sourceSystemCd) >= 0);
    return r;
};

const createNameResponse = (masterEntityId : string) : IMasterEntitySourceEntityNameResponse => {
    const r = { 
        getMasterEntitySourceEntityNameResponse: [
            {
                "masterEntityId": masterEntityId,
                "sourceEntityId": masterEntityId,
                "sourceSystemCd": "EROLL",
                "sourceEntityNameId": "34367802",
                "usageTypeCd": "MAIN",
                "standardFullName": "ADAM CHRISTOPHER SMITH",
                "organisationName": "",
                "namePrefix": "",
                "firstName": "ADAM",
                "middleName": "CHRISTOPHER",
                "familyName": "SMITH",
                "nameSuffix": "",
                "nameGeneration": "",
                "nameGenderCd": "M",
                "nameEntityTypeCd": "IND",
                "identifiedContactValue": " <NAMETYPE> I <TITLEFIRSTNAME> ADAM CHRISTOPHER <TITLEPRIMARYNAME> SMITH <ENDOFLINE> ",
                "effectiveStartDt": "2015-04-01"
            }, {
                "masterEntityId": masterEntityId,
                "sourceEntityId": "604455673",
                "sourceSystemCd": "ABR",
                "sourceEntityNameId": "713541716",
                "usageTypeCd": "TRD",
                "standardFullName": "ADAM SMITH",
                "organisationName": "ADAM SMITH",
                "namePrefix": "",
                "firstName": "",
                "middleName": "",
                "familyName": "",
                "nameSuffix": "",
                "nameGeneration": "",
                "nameGenderCd": "",
                "nameEntityTypeCd": "ORG",
                "identifiedContactValue": "<PRIMARYNAME> ADAM SMITH <ENDOFLINE>",
                "effectiveStartDt": "2006-01-01"
            }, {
                "masterEntityId": masterEntityId,
                "sourceEntityId": "604455673",
                "sourceSystemCd": "ABR",
                "sourceEntityNameId": "713541715",
                "usageTypeCd": "LGL",
                "standardFullName": "MR ADAM CHRISOPHER SMITH",
                "organisationName": "",
                "namePrefix": "MR",
                "firstName": "ADAM",
                "middleName": "CHRISOPHER",
                "familyName": "SMITH",
                "nameSuffix": "",
                "nameGeneration": "",
                "nameGenderCd": "M",
                "nameEntityTypeCd": "IND",
                "identifiedContactValue": "<NAMEPREFIX> MR <FIRSTNAME> ADAM <MIDDLENAME> CHRISOPHER <PRIMARYNAME> SMITH <NAMESUFFIX> <ENDOFLINE>",
                "effectiveStartDt": "2006-01-01"
            }, {
                "masterEntityId": masterEntityId,
                "sourceEntityId": "732560948",
                "sourceSystemCd": "ASIC",
                "sourceEntityNameId": "1006361313",
                "usageTypeCd": "MAIN",
                "standardFullName": "ADAM CHRISTOPHER SMITH",
                "organisationName": "",
                "namePrefix": "",
                "firstName": "ADAM",
                "middleName": "CHRISTOPHER",
                "familyName": "SMITH",
                "nameSuffix": "",
                "nameGeneration": "",
                "nameGenderCd": "M",
                "nameEntityTypeCd": "IND",
                "identifiedContactValue": "<FIRSTNAME> ADAM <MIDDLENAME> CHRISTOPHER <PRIMARYNAME> SMITH <ENDOFLINE>",
                "effectiveStartDt": "2007-07-27"
            }, {
                "masterEntityId": masterEntityId,
                "sourceEntityId": "746788568",
                "sourceSystemCd": "IAT",
                "sourceEntityNameId": "896845850",
                "usageTypeCd": "BRTH/MAIN",
                "standardFullName": "ADAM CHRISTOPHER SMITH",
                "organisationName": "",
                "namePrefix": "",
                "firstName": "ADAM",
                "middleName": "CHRISTOPHER",
                "familyName": "SMITH",
                "nameSuffix": "",
                "nameGeneration": "",
                "nameGenderCd": "M",
                "nameEntityTypeCd": "IND",
                "identifiedContactValue": "ADAM CHRISTOPHER SMITH",
                "effectiveStartDt": "2005-11-22"
            }, {
                "masterEntityId": masterEntityId,
                "sourceEntityId": "746788568",
                "sourceSystemCd": "IAT",
                "sourceEntityNameId": "896845850",
                "usageTypeCd": "BRTH/MAIN",
                "standardFullName": "ADAM CHRISTOPHER SMITH",
                "organisationName": "",
                "namePrefix": "",
                "firstName": "ADAM",
                "middleName": "CHRISTOPHER",
                "familyName": "SMITH",
                "nameSuffix": "",
                "nameGeneration": "",
                "nameGenderCd": "M",
                "nameEntityTypeCd": "IND",
                "identifiedContactValue": " <NAMETYPE> I <TITLEFIRSTNAME> ADAM CHRISTOPHER <TITLEPRIMARYNAME> SMITH <ENDOFLINE> ",
                "effectiveStartDt": "2005-11-22"
            }, {
                "masterEntityId": masterEntityId,
                "sourceEntityId": "1493584953",
                "sourceSystemCd": "ICS",
                "sourceEntityNameId": "149358495312",
                "usageTypeCd": "BRTH/MAIN",
                "standardFullName": "ADAM CHRISTOPHER SMITH",
                "organisationName": "",
                "namePrefix": "",
                "firstName": "ADAM",
                "middleName": "CHRISTOPHER",
                "familyName": "SMITH",
                "nameSuffix": "",
                "nameGeneration": "",
                "nameGenderCd": "M",
                "nameEntityTypeCd": "IND",
                "identifiedContactValue": " <NAMETYPE> I <TITLEFIRSTNAME> ADAM CHRISTOPHER <TITLEPRIMARYNAME> SMITH <ENDOFLINE> ",
                "effectiveStartDt": "2005-11-22"
            }, {
                "masterEntityId": masterEntityId,
                "sourceEntityId": "280514359",
                "sourceSystemCd": "BAGS",
                "sourceEntityNameId": "28051435912",
                "usageTypeCd": "BRTH/MAIN",
                "standardFullName": "ADAM CHRISTOPHER SMITH",
                "organisationName": "",
                "namePrefix": "",
                "firstName": "ADAM",
                "middleName": "CHRISTOPHER",
                "familyName": "SMITH",
                "nameSuffix": "",
                "nameGeneration": "",
                "nameGenderCd": "M",
                "nameEntityTypeCd": "IND",
                "identifiedContactValue": " <NAMETYPE> I <TITLEFIRSTNAME> ADAM CHRISTOPHER <TITLEPRIMARYNAME> SMITH <ENDOFLINE> ",
                "effectiveStartDt": "2005-11-22"
            }, {
                "masterEntityId": masterEntityId,
                "sourceEntityId": "1362633444",
                "sourceSystemCd": "DGMS",
                "sourceEntityNameId": "136263344412",
                "usageTypeCd": "BRTH/MAIN",
                "standardFullName": "ADAM CHRISTOPHER SMITH",
                "organisationName": "",
                "namePrefix": "",
                "firstName": "ADAM",
                "middleName": "CHRISTOPHER",
                "familyName": "SMITH",
                "nameSuffix": "",
                "nameGeneration": "",
                "nameGenderCd": "M",
                "nameEntityTypeCd": "IND",
                "identifiedContactValue": " <NAMETYPE> I <TITLEFIRSTNAME> ADAM CHRISTOPHER <TITLEPRIMARYNAME> SMITH <ENDOFLINE> ",
                "effectiveStartDt": "2005-11-22"
            }, {
                "masterEntityId": masterEntityId,
                "sourceEntityId": "1362633446",
                "sourceSystemCd": "IATA",
                "sourceEntityNameId": "12896845850",
                "usageTypeCd": "BRTH/MAIN",
                "standardFullName": "ADAM CHRISTOPHER SMITH",
                "organisationName": "",
                "namePrefix": "",
                "firstName": "ADAM",
                "middleName": "CHRISTOPHER",
                "familyName": "SMITH",
                "nameSuffix": "",
                "nameGeneration": "",
                "nameGenderCd": "M",
                "nameEntityTypeCd": "IND",
                "identifiedContactValue": " <NAMETYPE> I <TITLEFIRSTNAME> ADAM CHRISTOPHER <TITLEPRIMARYNAME> SMITH <ENDOFLINE> ",
                "effectiveStartDt": "2005-11-22"
            }, {
                "masterEntityId": masterEntityId,
                "sourceEntityId": "1362633447",
                "sourceSystemCd": "INTCP",
                "sourceEntityNameId": "12896845850",
                "usageTypeCd": "BRTH/MAIN",
                "standardFullName": "ADAM CHRISTOPHER SMITH",
                "organisationName": "",
                "namePrefix": "",
                "firstName": "ADAM",
                "middleName": "CHRISTOPHER",
                "familyName": "SMITH",
                "nameSuffix": "",
                "nameGeneration": "",
                "nameGenderCd": "M",
                "nameEntityTypeCd": "IND",
                "identifiedContactValue": " <NAMETYPE> I <TITLEFIRSTNAME> ADAM CHRISTOPHER <TITLEPRIMARYNAME> SMITH <ENDOFLINE> ",
                "effectiveStartDt": "2005-11-22"
            }
        ]
    };
    r.getMasterEntitySourceEntityNameResponse = r.getMasterEntitySourceEntityNameResponse.filter(r => sourceSystemCodes.indexOf(r.sourceSystemCd) >= 0);
    return r;
};

const createAddressResponse = (masterEntityId : string) : IMasterEntitySourceEntityAddressResponse => {
    const r = {
        getMasterEntitySourceEntityAddressResponse: [
            {
                "masterEntityId": masterEntityId,
                "sourceEntityId": masterEntityId,
                "sourceSystemCd": "EROLL",
                "sourceEntityAddressId": "34367803",
                "addressMatchKeyCd": "A01F",
                "addressSiteLatitude": "-37.835380000000000",
                "addressSiteLongitude": "144.879637000000000",
                "streetLocalityPointLatitude": "-37.835405190000000",
                "streetLocalityPointLongitude": "144.878303410000000",
                "localityPointLatitude": "-37.843600550000000",
                "localityPointLongitude": "144.880448570000000",
                "usageTypeCd": "RES",
                "standardAddressValue": "26 JUNCTION STREET NEWPORT VIC 3015 AU",
                "lotId": "",
                "unitTypeAbbreviation": "",
                "unitId": "",
                "levelTypeAbbreviation": "",
                "levelId": "",
                "roadFirstPartId": "26",
                "roadSecondPartId": "",
                "roadName": "JUNCTION",
                "roadTypeAbbreviation": "STREET",
                "roadSuffixAbbreviation": "",
                "addressSiteName": "",
                "localityName": "NEWPORT",
                "stateCd": "VIC",
                "postalCd": "3015",
                "countryCd": "AU",
                "administrationArea": "",
                "supraAdministrationArea": "",
                "subAdministrationArea": "",
                "postalDeliveryTypeAbbreviation": "",
                "postalDeliveryId": "",
                "deliveryPointId": "",
                "unparsedAddress": "",
                "identifiedContactValue": "<ADDRSLINE> 26 JUNCTION ST <ADDRSAREA> NEWPORT VIC 3015 AU",
                "usageTypeCdGeo": "RES",
                "standardAddressValueGeo": "26 JUNCTION STREET NEWPORT VIC 3015 AU",
                "lotIdGeo": "",
                "unitTypeAbbreviationGeo": "",
                "unitIdGeo": "",
                "levelTypeAbbreviationGeo": "",
                "levelIdGeo": "",
                "roadFirstPartIdGeo": "26",
                "roadSecondPartIdGeo": "",
                "roadNameGeo": "JUNCTION",
                "roadTypeAbbreviationGeo": "STREET",
                "roadSuffixAbbreviationGeo": "",
                "addressSiteNameGeo": "",
                "localityNameGeo": "NEWPORT",
                "stateCdGeo": "VIC",
                "postalCdGeo": "3015",
                "countryCdGeo": "AU",
                "postalDeliveryTypeAbbreviationGeo": "",
                "postalDeliveryIdGeo": "",
                "deliveryPointIdGeo": "",
                "addressSitePID": "420955862",
                "addressDetailPID": "GAVIC420812832",
                "streetLocalityPID": "VIC1981976",
                "localityPID": "VIC1930",
                "statePID": "2",
                "effectiveStartDt": "2015-04-01"
            }, {
                "masterEntityId": masterEntityId,
                "sourceEntityId": "604455673",
                "sourceSystemCd": "ABR",
                "sourceEntityAddressId": "669245190",
                "addressMatchKeyCd": "A01F",
                "addressSiteLatitude": "-37.835380000000000",
                "addressSiteLongitude": "144.879637000000000",
                "streetLocalityPointLatitude": "-37.835405190000000",
                "streetLocalityPointLongitude": "144.878303410000000",
                "localityPointLatitude": "-37.843600550000000",
                "localityPointLongitude": "144.880448570000000",
                "usageTypeCd": "BUS",
                "standardAddressValue": "26 JUNCTION STREET NEWPORT VIC 3015",
                "lotId": "",
                "unitTypeAbbreviation": "",
                "unitId": "",
                "levelTypeAbbreviation": "",
                "levelId": "",
                "roadFirstPartId": "26",
                "roadSecondPartId": "",
                "roadName": "JUNCTION",
                "roadTypeAbbreviation": "STREET",
                "roadSuffixAbbreviation": "",
                "addressSiteName": "",
                "localityName": "NEWPORT",
                "stateCd": "VIC",
                "postalCd": "3015",
                "countryCd": "",
                "administrationArea": "",
                "supraAdministrationArea": "",
                "subAdministrationArea": "",
                "postalDeliveryTypeAbbreviation": "",
                "postalDeliveryId": "",
                "deliveryPointId": "",
                "unparsedAddress": "",
                "identifiedContactValue": "<ADDRSLINE> 26 JUNCTION ST <ADDRSAREA> NEWPORT VIC 3015 AUS",
                "usageTypeCdGeo": "BUS",
                "standardAddressValueGeo": "26 JUNCTION STREET NEWPORT VIC 3015 AU",
                "lotIdGeo": "",
                "unitTypeAbbreviationGeo": "",
                "unitIdGeo": "",
                "levelTypeAbbreviationGeo": "",
                "levelIdGeo": "",
                "roadFirstPartIdGeo": "26",
                "roadSecondPartIdGeo": "",
                "roadNameGeo": "JUNCTION",
                "roadTypeAbbreviationGeo": "STREET",
                "roadSuffixAbbreviationGeo": "",
                "addressSiteNameGeo": "",
                "localityNameGeo": "NEWPORT",
                "stateCdGeo": "VIC",
                "postalCdGeo": "3015",
                "countryCdGeo": "AU",
                "postalDeliveryTypeAbbreviationGeo": "",
                "postalDeliveryIdGeo": "",
                "deliveryPointIdGeo": "",
                "addressSitePID": "420955862",
                "addressDetailPID": "GAVIC420812832",
                "streetLocalityPID": "VIC1981976",
                "localityPID": "VIC1930",
                "statePID": "2",
                "effectiveStartDt": "2006-01-01"
            }, {
                "masterEntityId": masterEntityId,
                "sourceEntityId": "604455673",
                "sourceSystemCd": "ABR",
                "sourceEntityAddressId": "669245191",
                "addressMatchKeyCd": "A01F",
                "addressSiteLatitude": "-37.835380000000000",
                "addressSiteLongitude": "144.879637000000000",
                "streetLocalityPointLatitude": "-37.835405190000000",
                "streetLocalityPointLongitude": "144.878303410000000",
                "localityPointLatitude": "-37.843600550000000",
                "localityPointLongitude": "144.880448570000000",
                "usageTypeCd": "POS",
                "standardAddressValue": "26 JUNCTION STREET NEWPORT VIC 3015",
                "lotId": "",
                "unitTypeAbbreviation": "",
                "unitId": "",
                "levelTypeAbbreviation": "",
                "levelId": "",
                "roadFirstPartId": "26",
                "roadSecondPartId": "",
                "roadName": "JUNCTION",
                "roadTypeAbbreviation": "STREET",
                "roadSuffixAbbreviation": "",
                "addressSiteName": "",
                "localityName": "NEWPORT",
                "stateCd": "VIC",
                "postalCd": "3015",
                "countryCd": "",
                "administrationArea": "",
                "supraAdministrationArea": "",
                "subAdministrationArea": "",
                "postalDeliveryTypeAbbreviation": "",
                "postalDeliveryId": "",
                "deliveryPointId": "",
                "unparsedAddress": "",
                "identifiedContactValue": "<ADDRSLINE> 26 JUNCTION ST <ADDRSAREA> NEWPORT VIC 3015 AUS",
                "usageTypeCdGeo": "POS",
                "standardAddressValueGeo": "26 JUNCTION STREET NEWPORT VIC 3015 AU",
                "lotIdGeo": "",
                "unitTypeAbbreviationGeo": "",
                "unitIdGeo": "",
                "levelTypeAbbreviationGeo": "",
                "levelIdGeo": "",
                "roadFirstPartIdGeo": "26",
                "roadSecondPartIdGeo": "",
                "roadNameGeo": "JUNCTION",
                "roadTypeAbbreviationGeo": "STREET",
                "roadSuffixAbbreviationGeo": "",
                "addressSiteNameGeo": "",
                "localityNameGeo": "NEWPORT",
                "stateCdGeo": "VIC",
                "postalCdGeo": "3015",
                "countryCdGeo": "AU",
                "postalDeliveryTypeAbbreviationGeo": "",
                "postalDeliveryIdGeo": "",
                "deliveryPointIdGeo": "",
                "addressSitePID": "420955862",
                "addressDetailPID": "GAVIC420812832",
                "streetLocalityPID": "VIC1981976",
                "localityPID": "VIC1930",
                "statePID": "2",
                "effectiveStartDt": "2006-01-01"
            }, {
                "masterEntityId": masterEntityId,
                "sourceEntityId": "732560948",
                "sourceSystemCd": "ASIC",
                "sourceEntityAddressId": "895055752",
                "addressMatchKeyCd": "A01F",
                "addressSiteLatitude": "-37.835380000000000",
                "addressSiteLongitude": "144.879637000000000",
                "streetLocalityPointLatitude": "-37.835405190000000",
                "streetLocalityPointLongitude": "144.878303410000000",
                "localityPointLatitude": "-37.843600550000000",
                "localityPointLongitude": "144.880448570000000",
                "usageTypeCd": "POS",
                "standardAddressValue": "26 JUNCTION STREET NEWPORT VIC 3015 AU",
                "lotId": "",
                "unitTypeAbbreviation": "",
                "unitId": "",
                "levelTypeAbbreviation": "",
                "levelId": "",
                "roadFirstPartId": "26",
                "roadSecondPartId": "",
                "roadName": "JUNCTION",
                "roadTypeAbbreviation": "STREET",
                "roadSuffixAbbreviation": "",
                "addressSiteName": "",
                "localityName": "NEWPORT",
                "stateCd": "VIC",
                "postalCd": "3015",
                "countryCd": "AU",
                "administrationArea": "",
                "supraAdministrationArea": "",
                "subAdministrationArea": "",
                "postalDeliveryTypeAbbreviation": "",
                "postalDeliveryId": "",
                "deliveryPointId": "",
                "unparsedAddress": "",
                "identifiedContactValue": "<ADDRSLINE> 26 JUNCTION ST <ADDRSAREA> NEWPORT VIC 3015",
                "usageTypeCdGeo": "POS",
                "standardAddressValueGeo": "26 JUNCTION STREET NEWPORT VIC 3015 AU",
                "lotIdGeo": "",
                "unitTypeAbbreviationGeo": "",
                "unitIdGeo": "",
                "levelTypeAbbreviationGeo": "",
                "levelIdGeo": "",
                "roadFirstPartIdGeo": "26",
                "roadSecondPartIdGeo": "",
                "roadNameGeo": "JUNCTION",
                "roadTypeAbbreviationGeo": "STREET",
                "roadSuffixAbbreviationGeo": "",
                "addressSiteNameGeo": "",
                "localityNameGeo": "NEWPORT",
                "stateCdGeo": "VIC",
                "postalCdGeo": "3015",
                "countryCdGeo": "AU",
                "postalDeliveryTypeAbbreviationGeo": "",
                "postalDeliveryIdGeo": "",
                "deliveryPointIdGeo": "",
                "addressSitePID": "420955862",
                "addressDetailPID": "GAVIC420812832",
                "streetLocalityPID": "VIC1981976",
                "localityPID": "VIC1930",
                "statePID": "2",
                "effectiveStartDt": "2007-07-27"
            }, {
                "masterEntityId": masterEntityId,
                "sourceEntityId": "732560948",
                "sourceSystemCd": "ASIC",
                "sourceEntityAddressId": "895055752",
                "addressMatchKeyCd": "A01F",
                "addressSiteLatitude": "-37.835380000000000",
                "addressSiteLongitude": "144.879637000000000",
                "streetLocalityPointLatitude": "-37.835405190000000",
                "streetLocalityPointLongitude": "144.878303410000000",
                "localityPointLatitude": "-37.843600550000000",
                "localityPointLongitude": "144.880448570000000",
                "usageTypeCd": "POS",
                "standardAddressValue": "26 JUNCTION STREET NEWPORT VIC 3015 AU",
                "lotId": "",
                "unitTypeAbbreviation": "",
                "unitId": "",
                "levelTypeAbbreviation": "",
                "levelId": "",
                "roadFirstPartId": "26",
                "roadSecondPartId": "",
                "roadName": "JUNCTION",
                "roadTypeAbbreviation": "STREET",
                "roadSuffixAbbreviation": "",
                "addressSiteName": "",
                "localityName": "NEWPORT",
                "stateCd": "VIC",
                "postalCd": "3015",
                "countryCd": "AU",
                "administrationArea": "",
                "supraAdministrationArea": "",
                "subAdministrationArea": "",
                "postalDeliveryTypeAbbreviation": "",
                "postalDeliveryId": "",
                "deliveryPointId": "",
                "unparsedAddress": "",
                "identifiedContactValue": "<ADDRSLINE> 26 JUNCTION ST <ADDRSAREA> NEWPORT VIC 3015",
                "usageTypeCdGeo": "POS",
                "standardAddressValueGeo": "26 JUNCTION STREET NEWPORT VIC 3015 AU",
                "lotIdGeo": "",
                "unitTypeAbbreviationGeo": "",
                "unitIdGeo": "",
                "levelTypeAbbreviationGeo": "",
                "levelIdGeo": "",
                "roadFirstPartIdGeo": "26",
                "roadSecondPartIdGeo": "",
                "roadNameGeo": "JUNCTION",
                "roadTypeAbbreviationGeo": "STREET",
                "roadSuffixAbbreviationGeo": "",
                "addressSiteNameGeo": "",
                "localityNameGeo": "NEWPORT",
                "stateCdGeo": "VIC",
                "postalCdGeo": "3015",
                "countryCdGeo": "AU",
                "postalDeliveryTypeAbbreviationGeo": "",
                "postalDeliveryIdGeo": "",
                "deliveryPointIdGeo": "",
                "addressSitePID": "420955862",
                "addressDetailPID": "GAVIC420812832",
                "streetLocalityPID": "VIC1981976",
                "localityPID": "VIC1930",
                "statePID": "2",
                "effectiveStartDt": "2010-08-24"
            }, {
                "masterEntityId": masterEntityId,
                "sourceEntityId": "732560948",
                "sourceSystemCd": "ASIC",
                "sourceEntityAddressId": "895055752",
                "addressMatchKeyCd": "A01F",
                "addressSiteLatitude": "-37.835380000000000",
                "addressSiteLongitude": "144.879637000000000",
                "streetLocalityPointLatitude": "-37.835405190000000",
                "streetLocalityPointLongitude": "144.878303410000000",
                "localityPointLatitude": "-37.843600550000000",
                "localityPointLongitude": "144.880448570000000",
                "usageTypeCd": "POS",
                "standardAddressValue": "26 JUNCTION STREET NEWPORT VIC 3015 AU",
                "lotId": "",
                "unitTypeAbbreviation": "",
                "unitId": "",
                "levelTypeAbbreviation": "",
                "levelId": "",
                "roadFirstPartId": "26",
                "roadSecondPartId": "",
                "roadName": "JUNCTION",
                "roadTypeAbbreviation": "STREET",
                "roadSuffixAbbreviation": "",
                "addressSiteName": "",
                "localityName": "NEWPORT",
                "stateCd": "VIC",
                "postalCd": "3015",
                "countryCd": "AU",
                "administrationArea": "",
                "supraAdministrationArea": "",
                "subAdministrationArea": "",
                "postalDeliveryTypeAbbreviation": "",
                "postalDeliveryId": "",
                "deliveryPointId": "",
                "unparsedAddress": "",
                "identifiedContactValue": "<ADDRSLINE> 26 JUNCTION ST <ADDRSAREA> NEWPORT VIC 3015",
                "usageTypeCdGeo": "POS",
                "standardAddressValueGeo": "26 JUNCTION STREET NEWPORT VIC 3015 AU",
                "lotIdGeo": "",
                "unitTypeAbbreviationGeo": "",
                "unitIdGeo": "",
                "levelTypeAbbreviationGeo": "",
                "levelIdGeo": "",
                "roadFirstPartIdGeo": "26",
                "roadSecondPartIdGeo": "",
                "roadNameGeo": "JUNCTION",
                "roadTypeAbbreviationGeo": "STREET",
                "roadSuffixAbbreviationGeo": "",
                "addressSiteNameGeo": "",
                "localityNameGeo": "NEWPORT",
                "stateCdGeo": "VIC",
                "postalCdGeo": "3015",
                "countryCdGeo": "AU",
                "postalDeliveryTypeAbbreviationGeo": "",
                "postalDeliveryIdGeo": "",
                "deliveryPointIdGeo": "",
                "addressSitePID": "420955862",
                "addressDetailPID": "GAVIC420812832",
                "streetLocalityPID": "VIC1981976",
                "localityPID": "VIC1930",
                "statePID": "2",
                "effectiveStartDt": "2010-08-26"
            }, {
                "masterEntityId": masterEntityId,
                "sourceEntityId": "732560948",
                "sourceSystemCd": "ASIC",
                "sourceEntityAddressId": "908366144",
                "addressMatchKeyCd": "A01F",
                "addressSiteLatitude": "-37.804189000000000",
                "addressSiteLongitude": "144.884028000000000",
                "streetLocalityPointLatitude": "-37.808146740000000",
                "streetLocalityPointLongitude": "144.883496210000000",
                "localityPointLatitude": "-37.808854680000000",
                "localityPointLongitude": "144.879432030000000",
                "usageTypeCd": "POS",
                "standardAddressValue": "8 QUEENSVILLE STREET KINGSVILLE VIC 3012 AU",
                "lotId": "",
                "unitTypeAbbreviation": "",
                "unitId": "",
                "levelTypeAbbreviation": "",
                "levelId": "",
                "roadFirstPartId": "8",
                "roadSecondPartId": "",
                "roadName": "QUEENSVILLE",
                "roadTypeAbbreviation": "STREET",
                "roadSuffixAbbreviation": "",
                "addressSiteName": "",
                "localityName": "KINGSVILLE",
                "stateCd": "VIC",
                "postalCd": "3012",
                "countryCd": "AU",
                "administrationArea": "",
                "supraAdministrationArea": "",
                "subAdministrationArea": "",
                "postalDeliveryTypeAbbreviation": "",
                "postalDeliveryId": "",
                "deliveryPointId": "",
                "unparsedAddress": "",
                "identifiedContactValue": "<ADDRSLINE> 8 QUEENSVILLE ST <ADDRSAREA> KINGSVILLE VIC 3012",
                "usageTypeCdGeo": "POS",
                "standardAddressValueGeo": "8 QUEENSVILLE STREET KINGSVILLE VIC 3012 AU",
                "lotIdGeo": "",
                "unitTypeAbbreviationGeo": "",
                "unitIdGeo": "",
                "levelTypeAbbreviationGeo": "",
                "levelIdGeo": "",
                "roadFirstPartIdGeo": "8",
                "roadSecondPartIdGeo": "",
                "roadNameGeo": "QUEENSVILLE",
                "roadTypeAbbreviationGeo": "STREET",
                "roadSuffixAbbreviationGeo": "",
                "addressSiteNameGeo": "",
                "localityNameGeo": "KINGSVILLE",
                "stateCdGeo": "VIC",
                "postalCdGeo": "3012",
                "countryCdGeo": "AU",
                "postalDeliveryTypeAbbreviationGeo": "",
                "postalDeliveryIdGeo": "",
                "deliveryPointIdGeo": "",
                "addressSitePID": "421487963",
                "addressDetailPID": "GAVIC421337896",
                "streetLocalityPID": "VIC2026012",
                "localityPID": "VIC1360",
                "statePID": "2",
                "effectiveStartDt": "2007-07-27"
            }
        ]
    };
    r.getMasterEntitySourceEntityAddressResponse = r.getMasterEntitySourceEntityAddressResponse.filter(r => sourceSystemCodes.indexOf(r.sourceSystemCd) >= 0);
    return r;
};

const createPhoneResponse = (masterEntityId : string) : IMasterEntitySourceEntityPhoneResponse => {
    return {
        "getMasterEntitySourceEntityPhoneResponse":[],"totalrecords":0
    };
};

const createCredentialResponse = (masterEntityId : string) : IMasterEntitySourceEntityCredentialResponse => {
    const r = {
        "getMasterEntitySourceEntityCredentialResponse": [
            {
                "masterEntityId": masterEntityId,
                "sourceEntityId": "604455673",
                "sourceSystemCd": "ABR",
                "sourceEntityCredentialId": "615939855",
                "credentialTypeCd": "ABN",
                "credentialValue": "11050292579",
                "internalIndicator": "N",
                "credentialCountryCd": "AUS",
                "issuingCountryCd": "AUS",
                "issuingAuthorityCd": "ABR",
                "effectiveStartDt": "2006-01-01"
            }, {
                "masterEntityId": masterEntityId,
                "sourceEntityId": "746788568",
                "sourceSystemCd": "IAT",
                "sourceEntityCredentialId": "869896102",
                "credentialTypeCd": "TD",
                "credentialValue": "H147374",
                "internalIndicator": "N",
                "credentialCountryCd": "AUS",
                "issuingCountryCd": "",
                "issuingAuthorityCd": "",
                "effectiveStartDt": "2005-11-20"
            }, {
                "masterEntityId": masterEntityId,
                "sourceEntityId": "746788568",
                "sourceSystemCd": "IAT",
                "sourceEntityCredentialId": "983865313",
                "credentialTypeCd": "TD",
                "credentialValue": "L0907145",
                "internalIndicator": "N",
                "credentialCountryCd": "AUS",
                "issuingCountryCd": "",
                "issuingAuthorityCd": "",
                "effectiveStartDt": "2007-05-25"
            }, {
                "masterEntityId": masterEntityId,
                "sourceEntityId": "746788568",
                "sourceSystemCd": "IAT",
                "sourceEntityCredentialId": "1022194506",
                "credentialTypeCd": "TD",
                "credentialValue": "M7029872",
                "internalIndicator": "N",
                "credentialCountryCd": "AUS",
                "issuingCountryCd": "",
                "issuingAuthorityCd": "",
                "effectiveStartDt": "2008-01-28"
            },
            {
                "masterEntityId": masterEntityId,
                "sourceEntityId": "746788568",
                "sourceSystemCd": "IAT",
                "sourceEntityCredentialId": "23423423",
                "credentialTypeCd": "VISA",
                "credentialValue": "M7029872",
                "internalIndicator": "N",
                "credentialCountryCd": "AUS",
                "issuingCountryCd": "",
                "issuingAuthorityCd": "",
                "effectiveStartDt": "2008-01-28"
            },
            {
                "masterEntityId": masterEntityId,
                "sourceEntityId": "746788568",
                "sourceSystemCd": "IAT",
                "sourceEntityCredentialId": "23423423",
                "credentialTypeCd": "VISA",
                "credentialValue": "M7029872",
                "internalIndicator": "N",
                "credentialCountryCd": "AUS",
                "issuingCountryCd": "",
                "issuingAuthorityCd": "",
                "effectiveStartDt": "2008-01-28"
            },
            {
                "masterEntityId": masterEntityId,
                "sourceEntityId": "746788568",
                "sourceSystemCd": "IAT",
                "sourceEntityCredentialId": "23423423",
                "credentialTypeCd": "VISA",
                "credentialValue": "M7029872",
                "internalIndicator": "N",
                "credentialCountryCd": "AUS",
                "issuingCountryCd": "",
                "issuingAuthorityCd": "",
                "effectiveStartDt": "2008-01-28"
            },
            {
                "masterEntityId": masterEntityId,
                "sourceEntityId": "746788568",
                "sourceSystemCd": "IAT",
                "sourceEntityCredentialId": "23423423",
                "credentialTypeCd": "VISA",
                "credentialValue": "M7029872",
                "internalIndicator": "N",
                "credentialCountryCd": "AUS",
                "issuingCountryCd": "",
                "issuingAuthorityCd": "",
                "effectiveStartDt": "2008-01-28"
            }
        ],
        "totalrecords": 8
    };
    r.getMasterEntitySourceEntityCredentialResponse = r.getMasterEntitySourceEntityCredentialResponse.filter(r => sourceSystemCodes.indexOf(r.sourceSystemCd) >= 0);
    return r;
}

class MockMasterEntityDataService implements IMasterEntityDataService {
    refResponseFactory : (masterEntityId : string) => IMasterEntitySourceRefResponse = createRefResponse;
    metaResponseFactory : (masterEntityId : string) => IMasterEntitySourceEntityMetaResponse = createMetaResponse;
    nameResponseFactory : (masterEntityId : string) => IMasterEntitySourceEntityNameResponse = createNameResponse;
    addressResponseFactory : (masterEntityId : string) => IMasterEntitySourceEntityAddressResponse = createAddressResponse;
    phoneResponseFactory : (masterEntityId : string) => IMasterEntitySourceEntityPhoneResponse = createPhoneResponse;
    credentialResponseFactory : (masterEntityId : string) => IMasterEntitySourceEntityCredentialResponse = createCredentialResponse;
    getMasterEntitySourceRef(masterEntityId: string, opts?: IMasterEntityServiceRequestOptions) : Promise<IMasterEntitySourceRefResponse> {
        return Promise.resolve(this.refResponseFactory(masterEntityId));
    }
    getMasterEntitySourceEntityMeta(masterEntityId: string, opts?: IMasterEntityServiceRequestOptions) : Promise<IMasterEntitySourceEntityMetaResponse> {
        return Promise.resolve(this.metaResponseFactory(masterEntityId));
    }
    getMasterEntitySourceEntityName(masterEntityId: string, opts?: IMasterEntityServiceRequestOptions) : Promise<IMasterEntitySourceEntityNameResponse> {
        return Promise.resolve(this.nameResponseFactory(masterEntityId));
    }
    getMasterEntitySourceEntityAddress(masterEntityId: string, opts?: IMasterEntityServiceRequestOptions) : Promise<IMasterEntitySourceEntityAddressResponse> {
        return Promise.resolve(this.addressResponseFactory(masterEntityId));
    }
    getMasterEntitySourceEntityPhone(masterEntityId: string, opts?: IMasterEntityServiceRequestOptions) : Promise<IMasterEntitySourceEntityPhoneResponse> {
        return Promise.resolve(this.phoneResponseFactory(masterEntityId));
    }
    getMasterEntitySourceEntityCredential(masterEntityId: string, opts?: IMasterEntityServiceRequestOptions) : Promise<IMasterEntitySourceEntityCredentialResponse> {
        return Promise.resolve(this.credentialResponseFactory(masterEntityId));
    }
}

export { MockMasterEntityDataService as default, MockMasterEntityDataService };

