import { OptionListModel } from "@twii/common/lib/model/OptionListModel";

const StreetTypeOptionListStore = new OptionListModel([
    { key:"ACCESS", text:"ACCESS" },
    { key:"AVENUE", text:"AVENUE" },
    { key:"BOULEVARD", text:"BOULEVARD" },
    { key:"CIRCLE", text:"CIRCLE" },
    { key:"CIRCUIT", text:"CIRCUIT" },
    { key:"CLOSE", text:"CLOSE" },
    { key:"COURT", text:"COURT" },
    { key:"COVE", text:"COVE" },
    { key:"CRESCENT", text:"CRESCENT" },
    { key:"DRIVE", text:"DRIVE" },
    { key:"ESPLANADE", text:"ESPLANADE" },
    { key:"FIRETRAIL", text:"FIRETRAIL" },
    { key:"FREEWAY", text:"FREEWAY" },
    { key:"GARDENS", text:"GARDENS" },
    { key:"GREEN", text:"GREEN" },
    { key:"GROVE", text:"GROVE" },
    { key:"HIGHWAY", text:"HIGHWAY" },
    { key:"LANE", text:"LANE" },
    { key:"LINK", text:"LINK" },
    { key:"LOOP", text:"LOOP" },
    { key:"MEWS", text:"MEWS" },
    { key:"MOTORWAY", text:"MOTORWAY" },
    { key:"PARADE", text:"PARADE" },
    { key:"PARKWAY", text:"PARKWAY" },
    { key:"PASS", text:"PASS" },
    { key:"PATHWAY", text:"PATHWAY" },
    { key:"PLACE", text:"PLACE" },
    { key:"RAMP", text:"RAMP" },
    { key:"RETREAT", text:"RETREAT" },
    { key:"RISE", text:"RISE" },
    { key:"ROAD", text:"ROAD" },
    { key:"SQUARE", text:"SQUARE" },
    { key:"STREET", text:"STREET" },
    { key:"TERRACE", text:"TERRACE" },
    { key:"TRACK", text:"TRACK" },
    { key:"TRAIL", text:"TRAIL" },
    { key:"TURN", text:"TURN" },
    { key:"VIEW", text:"VIEW" },
    { key:"WALK", text:"WALK" },
    { key:"WAY", text:"WAY" }
]);

export { StreetTypeOptionListStore };