import MasterEntitySearchServiceContext from "entity/MasterEntitySearchServiceContext";
import MockMasterEntitySearchService from "entity/MockMasterEntitySearchService";
import MasterEntityDataServiceContext from "entity/MasterEntityDataServiceContext";
import MockMasterEntityDataService from "entity/MockMasterEntityDataService";
import IATServiceContext from "iat/IATServiceContext";
import MockIATService from "iat/MockIATService";
import BAGSServiceContext from "bags/BAGSServiceContext";
import MockBAGSService from "bags/MockBAGSService";
import EXAMSServiceContext from "exams/EXAMSServiceContext";
import MockEXAMSService from "exams/MockEXAMSService";
import DGMSServiceContext from "dgms/DGMSServiceContext";
import MockDGMSService from "dgms/MockDGMSService";
import AirCargoServiceContext from "cargo/air/AirCargoServiceContext";
import MockAirCargoService from "cargo/air/MockAirCargoService";
import SeaCargoServiceContext from "cargo/sea/SeaCargoServiceContext";
import MockSeaCargoService from "cargo/sea/MockSeaCargoService";
import MockIATAService from "iata/MockIATAService";
import IATAServiceContext from "iata/IATAServiceContext";
import MockINTCPService from "intcp/MockINTCPService";
import INTCPServiceContext from "intcp/INTCPServiceContext";
import UserServiceContext from "user/UserServiceContext";
import MockUserService from "user/MockUserService";
import ListingServiceContext from "listing/ListingServiceContext";
import { RestListingService } from "listing/RestListingService";
import MockListingService from "listing/MockListingService";
import PNRServiceContext from "pnr/PNRServiceContext";
import MockPNRService from "pnr/MockPNRService";
import TransientStorageService from "common/TransientStorageService";
import LoggingStorageService from "common/LoggingStorageService";
import StorageServiceContext from "common/StorageServiceContext";
import DashboardStorageServiceContext from "dashboard/DashboardStorageServiceContext";
import ImageServiceContext from "media/ImageServiceContext";
import { RestImageService } from "media/RestImageService";

const mockConfigurer = () => {
    console.log("-- Mock Configurer");
    UserServiceContext.value = new MockUserService();
    MasterEntitySearchServiceContext.value = new MockMasterEntitySearchService();
    MasterEntityDataServiceContext.value = new MockMasterEntityDataService();
    IATServiceContext.value = new MockIATService();
    BAGSServiceContext.value = new MockBAGSService();
    EXAMSServiceContext.value = new MockEXAMSService();
    DGMSServiceContext.value = new MockDGMSService();
    AirCargoServiceContext.value = new MockAirCargoService();
    SeaCargoServiceContext.value = new MockSeaCargoService();
    IATAServiceContext.value = new MockIATAService();
    INTCPServiceContext.value = new MockINTCPService();
    PNRServiceContext.value = new MockPNRService();
    //ListingServiceContext.value = new MockListingService();
    //ImageServiceContext.value = new MockImageService();
    const auth = { username: "bigbrother", password: "password" };
    ListingServiceContext.value = new RestListingService({ baseUrl: "http://localhost:8000/api", auth: auth });
    ImageServiceContext.value = new RestImageService({ baseUrl: "http://localhost:8000/api", auth: auth });
    StorageServiceContext.value = new TransientStorageService();
    DashboardStorageServiceContext.value = new LoggingStorageService(new TransientStorageService(), "mockStorage");
};

export { mockConfigurer as default, mockConfigurer };