interface IIATFlightListItem {
    iatTravellerIdentifier: string;
    aliasSequenceNbr?: string;
    birthDate?: string;
    sexCode?: string;
    familyName?: string;
    givenNames?: string;
    travelDocumentId?: string;
    travelDocCountryCode?: string;
    routeId: string;
    fullRoutingText?: string;
    localPortCode?: string;
    localScheduledDate: string;
    directionCode: string;
    actualMovementMessageID?: string;
    checkInPortCode?: string;
    expectedMovementMessageID?: string;
    expectedMovementNbr?: string;
    movementDate?: string;
    movementStatusCode?: string;
    movementTime?: string;
    movementHistoryInd?: string;
    visaIdentifyingNBR?: string;
    visaSubClassCode?: string;
    passengerCrewCode?: string;
    postMovementInd?: string;
    bagsExamReferralReasonCode?: string;
    travelDocSequenceNbr?: string;
    sourceSystemCode?: string;
    travellerMovementTypeCode?: string;
    birthDeptCountryCode?: string;
    visaID?: string;
    visaGrantDate?: string;
    alertInd?: string;
    movementRaceID?: string;
    userID?: string;
    numberOfExamsForTheTraveller?: string;
    positiveFindCountForTraveller?: string;
    examinationForTravellerInd?: string;
    positiveFindForTravellerInd?: string;
}

export { IIATFlightListItem as default, IIATFlightListItem };