import IIATAService from "./IIATAService";
import IIATAAgency from "./IIATAAgency";
import IIATAAgencyDetail from "./IIATAAgencyDetail";

class MockIATAService implements IIATAService {
    getIATAAgenciesResponse : IIATAAgency[] = [
        {
			"iataTravelAgencyCode": "TA4387583",
			"iataTravelAgencyCheckDigit": "3",
			"travelAgencyTypeCode": "HO",
			"carrierCode": "BNE",
			"travelAgencyName": "Travel World Pty Ltd",
			"tradingName": "Travel World",
			"locationCity": "Singapore",
			"locationRegion": "Singapore",
            "locationCountryCode": "SG",
            "telephoneCountryCode": "61",
            "telephoneAreaCode": "7",
			"telephoneNumber": "890264",
			"emailAddress": "test@test.com",
			"webAddress": "www.test.com"
		}
    ];
    getIATAAgencies(iataTravelAgencyId: string) : Promise<IIATAAgency[]> {
        return Promise.resolve(this.getIATAAgenciesResponse);
    }
    getIATAAgencyDetailsResponse : IIATAAgencyDetail[] = [
        {
			"recordIdentifier": "",
            "fileIdentifier": "TM",
            "iataArea": "1",
            "iataCode": "TA4387583",
            "iataCodeCheckDigit": "3",
            "cassNumber": "",
            "locationType": "HO",
            "airlineCode": "",
            "legalName1": "TRAVEL WORLD PTY LTD",
            "legalName2": "",
            "legalName3": "",
            "travelAgencyName": "TRAVEL WORLD PTY LTD",
            "fullTradingName": "",
            "locationAddress1": "53 OGDEN AVENUE",
            "locationAddress2": "",
            "locationAddress3": "",
            "locationCity": "CLARENDON HILLS",
            "locationStateCode": "ILLINOIS",
            "locationIsoCountryCode": "IL",
            "locationCountryCode": "U.S.A.",
            "loationCountryStatePostalAbbrvtn": "US",
            "locationIataCountryCode": "14",
            "locationPostalCode": "60514",
            "mailingAddress1": "53 OGDEN AVE",
            "mailingAddress2": "",
            "mailingCity": "CLARENDON HILLS",
            "mailingStateName": "ILLINOIS",
            "mailingCountryStatePostalAbbrvtn": "IL",
            "mailingCountryCode": "U.S.A.",
            "mailingIsoCountryCode": "US",
            "mailingIataCountryCode": "14",
            "mailingPostalCode": "60514-1026",
            "phone1InternationalDialCode": "1",
            "phone1StdCode": "630",
            "telephone1Number": "928-7100",
            "phone2InternationalDialCode": "",
            "phone2StdCode": "",
            "telephone2Number": "",
            "faxInternationalDialingCode": "1",
            "faxStdCode": "866",
            "faxNumber": "913-0138",
            "tollFreeInternationalDialingCode": "",
            "tollFreeStdCode": "",
            "tollFreeNumber": "",
            "emailAddressofLocation": "adam.smith@testiataworld.com",
            "webSiteAddressofLocation": "www.testiataworld.com",
            "telexTeletypeNumber": "",
            "crossReferenceArea": "",
            "crossReferenceIataCode": "",
            "crossReferenceIataCheckDigit": " ",
            "locationCategory1": "TA",
            "locationCategory2": "",
            "locationCategory3": "",
            "passengerOrCargoIndicator": "P",
            "companyType": "C",
            "solicitationFlag": "Y",
            "qualifiedTicketAgentLastName": "",
            "qualifiedTicketAgentFirstName": "",
            "locationManagerLastName": "SMITH",
            "locationManagerFirstName": "ADAM",
            "taxReferenceNumber": "",
            "otherTaxReferenceNumber": "",
            "computerReservationNumber1": "AP",
            "computerReservationNumber2": "SA",
            "computerReservationNumber3": "",
            "computerReservationNumber4": "",
            "organisation1LastChangeDate": "2014-12-23",
            "organisation1LastReinspectionDate": "2010-07-28",
            "organisation1OriginalApprovalDate": "1979-10-01",
            "organisation1LocationEndorsedBy": "IATAN",
            "organisation1EndorsementStatusCode": "7",
            "organisation1StatusAttainedDate": "1990-08-24",
            "organisation1LocationClass": "P",
            "organisation2LastChangeDate": "",
            "organisation2LastReinspectionDate": "",
            "organisation2OriginalApprovalDate": "",
            "organisation2LocationEndorsedBy": "",
            "organisation2EndorsementStatusCode": "",
            "organisation2StatusAttainedDate": "",
            "organisation2LocationClass": "",
            "bspOrCassCode": "",
            "agentRefNumber": "",
            "agentRefNumberForCrossReferencedParent": "",
            "associationMembershipandAffiliations1": "",
            "associationMembershipandAffiliations2": "",
            "agentLicenseNumber": "N",
            "languageofCorrespondence": "ENG",
            "fileVersion": "VERSION 1999",
            "fileProdDate": "2014-12-31",
            "fileName": "PASW",
            "fileLoadedTimeStamp": "2015-05-19 11:55:28.182551"
		}
    ];
    getIATAAgencyDetails(iataTravelAgencyId: string) : Promise<IIATAAgencyDetail[]> {
        return Promise.resolve(this.getIATAAgencyDetailsResponse);
    }
}

export { MockIATAService as default, MockIATAService }